(function(root){
 'use strict';
 const $=id=>document.getElementById(id),S=root.CardStore,store=S.create(()=>root.getCardContext());
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
 let rows=[],owner='',loaded=false,busy=false,edit=null,generation=0,focus=null,undo=null;
 const money=n=>n==null?'미입력':Number(n)===0?'없음':Number(n).toLocaleString()+'원';
 function mount(host){host.innerHTML=`<div class="cm-toolbar"><div><button id="cm-refresh">새로고침</button><button id="cm-add" class="cm-primary">+ 카드 추가</button></div></div><p id="cm-message" role="status"></p><button id="cm-undo" hidden>삭제 취소</button><div id="cm-list"></div><dialog id="cm-dialog" aria-labelledby="cm-title"><form id="cm-form"><header><h3 id="cm-title"></h3><button type="button" id="cm-close" aria-label="닫기">×</button></header><fieldset id="cm-fields"></fieldset><p id="cm-error" role="alert"></p><div id="cm-confirm" hidden><p>이 카드를 목록에서 삭제할까요?</p><button type="button" id="cm-confirm-yes">삭제 확인</button><button type="button" id="cm-confirm-no">돌아가기</button></div><footer><button type="button" id="cm-delete" class="cm-danger">삭제</button><button type="button" id="cm-cancel">취소</button><button id="cm-save" class="cm-primary">저장</button></footer></form></dialog>`;
 $('cm-header')?.appendChild(host.querySelector('.cm-toolbar'));
 $('cm-undo').onclick=restoreLast;
 $('cm-add').onclick=()=>open();$('cm-refresh').onclick=load;$('cm-close').onclick=close;$('cm-cancel').onclick=close;
 $('cm-dialog').oncancel=e=>{e.preventDefault();close();};$('cm-form').onsubmit=e=>{e.preventDefault();persist();};
 $('cm-delete').onclick=()=>{if(edit?.base?.deleted)persist(false);else {$('cm-confirm').hidden=false;$('cm-confirm-yes').focus();}};
 $('cm-confirm-yes').onclick=()=>persist(true);$('cm-confirm-no').onclick=()=>{$('cm-confirm').hidden=true;$('cm-delete').focus();};
 }
 function controls(){for(const id of ['cm-add','cm-refresh','cm-undo'])$(id).disabled=busy||!!edit||!owner||(id==='cm-add'&&!loaded);for(const id of ['cm-close','cm-cancel','cm-delete','cm-save','cm-confirm-yes','cm-confirm-no'])$(id).disabled=busy;$('cm-fields').disabled=busy||!!edit?.base?.deleted;document.querySelectorAll('#cm-list [data-card]').forEach(b=>b.disabled=busy||!!edit);}
 function card(c){const url=S.imageUrl(c.image_data);const image=url?`<img src="${esc(url)}" alt="${esc(c.name)} 카드 이미지" loading="lazy" referrerpolicy="no-referrer">`:'';return `<article class="cm-card"><header>${image}<div><h4>${esc(c.name)}</h4><small>${esc(c.bank)} · ${S.types[c.card_type]||'미지정'} · ${S.statuses[c.card_status]||'사용 중'}</small></div><button data-card="${c.id}" aria-label="${esc(c.name)} ${c.deleted?'복원':'수정'}">${c.deleted?'복원':'수정'}</button></header>${c.purpose?`<p>${esc(c.purpose)}</p>`:''}<div class="cm-facts"><span>전월실적 <b>${money(c.target_amt)}</b></span><span>연회비 <b>${money(c.annual_fee)}</b></span><span>결제일 <b>${c.pay_day?`${c.pay_day}일`:'미입력'}</b></span></div>${c.benefits?`<p class="cm-benefits">${esc(c.benefits)}</p>`:''}${c.prt_ideal||c.prt_real?`<small>피킹률 · 목표 ${esc(c.prt_ideal||'—')} / 실제 ${esc(c.prt_real||'—')}</small>`:''}</article>`;}
 function draw(){const active=rows.filter(c=>!c.deleted&&c.card_status!=='closed');
 $('cm-list').innerHTML=!owner?'<p>로그인 후 카드 정보를 관리할 수 있습니다.</p>':!loaded?'<p>새로고침으로 카드 정보를 불러오세요.</p>':(active.map(card).join('')||'<p>등록된 카드가 없습니다.</p>');
 $('cm-list').querySelectorAll('img').forEach(img=>img.onerror=()=>{img.hidden=true;});
 $('cm-undo').hidden=!undo;
 $('cm-list').querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>open(rows.find(c=>String(c.id)===b.dataset.card)));controls();}
 function open(base=null){if(busy||edit||!loaded)return;focus=document.activeElement;edit={base:base?{...base}:null,key:root.crypto.randomUUID()};const c=base||{card_type:'unspecified',card_status:'active'};
 const input=(key,label,type='text',attrs='')=>`<label>${label}<input name="${key}" type="${type}" ${attrs} value="${esc(c[key])}"></label>`;
 const select=(key,label,values)=>`<label>${label}<select name="${key}">${Object.entries(values).map(([k,v])=>`<option value="${k}"${c[key]===k?' selected':''}>${v}</option>`).join('')}</select></label>`;
 $('cm-title').textContent=base?.deleted?'카드 복원':base?'카드 수정':'카드 추가';
 $('cm-fields').innerHTML=`<div class="cm-grid">${input('name','카드명','text','required maxlength="120"')}${input('bank','카드사','text','required maxlength="100"')}${select('card_type','종류',S.types)}${input('purpose','주 사용처','text','maxlength="200"')}${input('pay_day','결제일 (일)','number','min="1" max="31" step="1"')}${input('target_amt','전월실적 조건 (원)','number','min="0" step="1"')}${input('annual_fee','연회비 (원)','number','min="0" step="1"')}${input('issued_on','발급일','date','min="1900-01-01" max="2200-12-31"')}</div><label>주요 혜택<textarea name="benefits" maxlength="2000" rows="3">${esc(c.benefits)}</textarea></label><label>메모<textarea name="note" maxlength="2000" rows="2">${esc(c.note)}</textarea></label><small>빈 금액은 미입력, 0원은 없음으로 표시합니다. 카드번호·CVC·비밀번호는 입력하지 마세요.</small>`;
 $('cm-error').textContent='';$('cm-confirm').hidden=true;$('cm-delete').hidden=!base;$('cm-delete').textContent=base?.deleted?'복원':'삭제';$('cm-save').hidden=!!base?.deleted;controls();$('cm-dialog').showModal();(base?.deleted?$('cm-delete'):$('cm-fields').querySelector('input')).focus();}
 function close(){if(busy)return;edit=null;$('cm-dialog').close();controls();if(focus?.isConnected)focus.focus();else $('cm-add').focus();}
 async function persist(deleted){if(busy||!edit)return;if(deleted===undefined&&edit.base?.deleted)return;const current=edit,token=generation,input={...Object.fromEntries(new FormData($('cm-form'))),card_status:edit.base?.card_status||'active'};busy=true;controls();$('cm-error').textContent='';
 try{const result=deleted===undefined?await store.save(input,current.base,current.key):await store.trash(current.base,deleted);if(token!==generation)return;rows=[...rows.filter(c=>c.id!==result.id),result];if(deleted===true)undo=result;busy=false;close();draw();$('cm-message').textContent=deleted===true?'목록에서 삭제했습니다.':deleted===false?'복원했습니다.':'저장했습니다.';}
 catch(e){if(token===generation)$('cm-error').textContent=e.message;}finally{if(token===generation){busy=false;controls();}}}
 async function restoreLast(){if(busy||edit||!undo)return;const token=generation;busy=true;controls();try{const result=await store.trash(undo,false);if(token!==generation)return;rows=rows.map(c=>c.id===result.id?result:c);undo=null;draw();$('cm-message').textContent='삭제를 취소했습니다.';}catch(e){if(token===generation)$('cm-message').textContent=e.message;}finally{if(token===generation){busy=false;controls();}}}
 async function load(){if(busy||edit||!owner)return;const token=generation;busy=true;controls();$('cm-message').textContent='불러오는 중…';try{const data=await store.list();if(token!==generation)return;rows=data;loaded=true;draw();$('cm-message').textContent='';}catch(e){if(token===generation)$('cm-message').textContent=e.message;}finally{if(token===generation){busy=false;controls();}}}
 function reset(){generation++;$('cm-dialog')?.close();rows=[];owner='';loaded=false;busy=false;edit=null;focus=null;undo=null;$('cm-header')?.querySelector('.cm-toolbar')?.remove();$('addon-cards-list')?.replaceChildren();}
 function render(){const host=$('addon-cards-list');if(!host)return;const id=root.getCardContext()?.userId||'';if(owner!==id)reset();owner=id;if(!$('cm-form'))mount(host);if(edit)return;draw();if(owner&&!loaded)load();}
 root.CardManager=Object.freeze({render,refresh:load,reset});
})(globalThis);
