param(
    [string]$RepoPath = "$PSScriptRoot\..\tools\external\real-estate-mcp",
    [string]$DataGoKrApiKey = "",
    [string]$OdcloudApiKey = "",
    [string]$OdcloudServiceKey = "",
    [string]$OnbidApiKey = ""
)

$ErrorActionPreference = "Stop"

$repoFullPath = [System.IO.Path]::GetFullPath($RepoPath)
if (-not (Test-Path $repoFullPath)) {
    throw "real-estate-mcp repo not found. Run scripts\install-realestate-mcp.ps1 first."
}

if (-not $DataGoKrApiKey -and -not $OdcloudApiKey -and -not $OdcloudServiceKey) {
    throw "Set at least one key: -DataGoKrApiKey, -OdcloudApiKey, or -OdcloudServiceKey."
}

$envPath = Join-Path $repoFullPath ".env"
$lines = @(
    "# Generated by NetVisualizer scripts/set-realestate-mcp-secrets.ps1",
    "# This file lives under tools/external/ and is ignored by Git."
)

if ($DataGoKrApiKey) { $lines += "DATA_GO_KR_API_KEY=$DataGoKrApiKey" }
if ($OdcloudApiKey) { $lines += "ODCLOUD_API_KEY=$OdcloudApiKey" }
if ($OdcloudServiceKey) { $lines += "ODCLOUD_SERVICE_KEY=$OdcloudServiceKey" }
if ($OnbidApiKey) { $lines += "ONBID_API_KEY=$OnbidApiKey" }

Set-Content -LiteralPath $envPath -Value $lines -Encoding UTF8

Write-Host "real-estate MCP .env updated:"
Write-Host $envPath
