import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { build } from 'vite';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
await build({ configFile: false, build: { emptyOutDir: false, outDir: fileURLToPath(new URL('vendor', root)), lib: {
  entry: fileURLToPath(new URL('node_modules/@supabase/supabase-js/dist/index.mjs', root)),
  name: 'supabase', formats: ['iife'], fileName: () => 'supabase.js',
}, minify: true, sourcemap: false } });
const html = await readFile(new URL('index.html', root), 'utf8');
const refs = [...html.matchAll(/<(?:script|link)\b[^>]*\b(?:src|href)=["'](\.\/[^"']+)["']/g)].map(m => m[1]);
const assets = [...new Set(['./', './index.html', './manifest.json', ...refs])].sort();
const hash = createHash('sha256');
for (const ref of [...assets, './sw.js']) {
  const path = ref === './' ? 'index.html' : ref.split('?')[0];
  const bytes = await readFile(new URL(path, root));
  hash.update(ref);
  // Git may check out CRLF on Windows and LF in CI; revision stays identical.
  let content = /\.(?:html|js|css|json|svg)$/.test(path) ? bytes.toString('utf8').replace(/\r\n/g, '\n') : bytes;
  if (path === 'index.html') content = content.replace(/(<meta name="app-build" content=")[^"]*(">)/, '$1BUILD$2');
  hash.update(content);
}
const revision = hash.digest('hex').slice(0, 16);
await writeFile(new URL('index.html', root), html.replace(/(<meta name="app-build" content=")[^"]*(">)/, `$1${revision}$2`));
await writeFile(new URL('version.json', root), JSON.stringify({revision}, null, 2)+'\n');
await writeFile(new URL('offline-assets.js', root), `// Generated by npm run build:offline. Do not edit.\nself.NETVISUALIZER_OFFLINE = ${JSON.stringify({ revision, assets }, null, 2)};\n`);
console.log(`Offline manifest: ${assets.length} assets, ${revision}`);
